[pytest]
testpaths = tests
norecursedirs =
    .venv
    __pycache__
    .pytest_tmp
    pytest_tmp_brand
    pytest-temp
    pytest-cache-files-*
    .pytest_cache
addopts = -ra -p no:cacheprovider --basetemp=pytest-temp
